name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Extract Docker imahe metadata
          id: metadata
          uses: docker/metadata-actions@v5
          with:
            images: ${{secrets.DOCKER_USERNAME}}/disaster_insurance

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and Push Docker Image
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ${{secrets.DOCKER_USERNAME}}/disaster_insurance:v1

         