name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-actions@v5
        with:
          images: ${{secrets.DOCKER_USERNAME}}/disaster_insurance

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and pushDocker image
        uses: docker/build-push-actions@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/disaster_insurance:v1